spring:
  datasource:
    driven-class-name: org.h2.Driver
    url: jdbc:h2:mem:people
    username: sa
    password:

  jpa:
    hibernate:
          ddl:-auto: update

  h2:
    console:
      enabled: true
      path: /database


  sql:
      init:
        platform: h2




